spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/plantdb
    username: postgres
    password: Pg18@2025
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

# Webhook（Local 用）
app:
  webhook:
    watering-url: http://host.docker.internal:8081/webhooks/watering